### ISSUE TITLE
Add Local Authentication using Passport

### ISSUE THREAD

**Issue by dyarawilliams** [dyarawilliams/book-up#4]
#### Description
The project did not have authentication for users. So It would be great if local authentication could be added using passport-local authentication.

#### Tasks
- [x] Install needed dependencies (bcrypt, connect-mongo, express-flash, express-session, passport, passport-local, and validator)
- [x] Create a dashboard layout and render the dashboard ejs with login and sign up 
- [x] Add routes for authentication
