### ISSUE TITLE
Edit Page is not working 

### ISSUE THREAD

**Issue by dyarawilliams** [dyarawilliams/book-up#8]
### **Description:**
When on the /books/:id route and you click on the edit icon which should direct you to the edit page of that book it redirects back to the /book route. This means that there is an error somewhere.

Screen recording: 

[Untitled_ Jan 22, 2024 12_41 AM.webm](https://github.com/dyarawilliams/book-up/assets/15236104/80d19049-7661-4582-9c21-ef2b076afe44)

### **Tasks:** 

- [ ]  Find the issue with the /books/:id/edit route.
- [ ] Make sure that the icon is directed to the edit page of the book you are trying to edit
- [ ] Log the error and explain how you corrected it
